# Generated by Django 2.2.14 on 2020-07-08 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20200708_1158'),
        ('user', '0003_auto_20200224_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='積點原因')),
                ('point', models.IntegerField(default=0, verbose_name='點數')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='積點時間')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
