# Generated by Django 2.2.6 on 2020-07-25 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_pointhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(1, '非常不同意'), (2, '不同意'), (3, '同意'), (4, '非常同意')], default=0)),
                ('q2', models.IntegerField(choices=[(1, '非常不同意'), (2, '不同意'), (3, '同意'), (4, '非常同意')], default=0)),
                ('q3', models.IntegerField(choices=[(1, '非常不同意'), (2, '不同意'), (3, '同意'), (4, '非常同意')], default=0)),
                ('t1', models.TextField(default='')),
                ('t2', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
